# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import eventoSolidario_pb2 as eventoSolidario__pb2
import usuario_pb2 as usuario__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eventoSolidario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventoSolidarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEventoSolidario = channel.unary_unary(
            '/EventoSolidarioService/CreateEventoSolidario',
            request_serializer=eventoSolidario__pb2.EventoSolidarioDTO.SerializeToString,
            response_deserializer=eventoSolidario__pb2.EventoSolidario.FromString,
            _registered_method=True)
        self.GetEventoSolidario = channel.unary_unary(
            '/EventoSolidarioService/GetEventoSolidario',
            request_serializer=eventoSolidario__pb2.EventoIdRequest.SerializeToString,
            response_deserializer=eventoSolidario__pb2.EventoSolidario.FromString,
            _registered_method=True)
        self.UpdateEventoSolidario = channel.unary_unary(
            '/EventoSolidarioService/UpdateEventoSolidario',
            request_serializer=eventoSolidario__pb2.EventoSolidarioDTO.SerializeToString,
            response_deserializer=eventoSolidario__pb2.EventoSolidario.FromString,
            _registered_method=True)
        self.DeleteEventoSolidario = channel.unary_unary(
            '/EventoSolidarioService/DeleteEventoSolidario',
            request_serializer=eventoSolidario__pb2.EventoIdRequest.SerializeToString,
            response_deserializer=eventoSolidario__pb2.EventoSolidario.FromString,
            _registered_method=True)
        self.ListEventoSolidarios = channel.unary_unary(
            '/EventoSolidarioService/ListEventoSolidarios',
            request_serializer=usuario__pb2.Empty.SerializeToString,
            response_deserializer=eventoSolidario__pb2.EventoSolidarioListResponse.FromString,
            _registered_method=True)


class EventoSolidarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEventoSolidario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventoSolidario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEventoSolidario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEventoSolidario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEventoSolidarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventoSolidarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateEventoSolidario': grpc.unary_unary_rpc_method_handler(
            servicer.CreateEventoSolidario,
            request_deserializer=eventoSolidario__pb2.EventoSolidarioDTO.FromString,
            response_serializer=eventoSolidario__pb2.EventoSolidario.SerializeToString,
        ),
        'GetEventoSolidario': grpc.unary_unary_rpc_method_handler(
            servicer.GetEventoSolidario,
            request_deserializer=eventoSolidario__pb2.EventoIdRequest.FromString,
            response_serializer=eventoSolidario__pb2.EventoSolidario.SerializeToString,
        ),
        'UpdateEventoSolidario': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateEventoSolidario,
            request_deserializer=eventoSolidario__pb2.EventoSolidarioDTO.FromString,
            response_serializer=eventoSolidario__pb2.EventoSolidario.SerializeToString,
        ),
        'DeleteEventoSolidario': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteEventoSolidario,
            request_deserializer=eventoSolidario__pb2.EventoIdRequest.FromString,
            response_serializer=eventoSolidario__pb2.EventoSolidario.SerializeToString,
        ),
        'ListEventoSolidarios': grpc.unary_unary_rpc_method_handler(
            servicer.ListEventoSolidarios,
            request_deserializer=usuario__pb2.Empty.FromString,
            response_serializer=eventoSolidario__pb2.EventoSolidarioListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'EventoSolidarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EventoSolidarioService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class EventoSolidarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEventoSolidario(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventoSolidarioService/CreateEventoSolidario',
            eventoSolidario__pb2.EventoSolidarioDTO.SerializeToString,
            eventoSolidario__pb2.EventoSolidario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventoSolidario(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventoSolidarioService/GetEventoSolidario',
            eventoSolidario__pb2.EventoIdRequest.SerializeToString,
            eventoSolidario__pb2.EventoSolidario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEventoSolidario(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventoSolidarioService/UpdateEventoSolidario',
            eventoSolidario__pb2.EventoSolidarioDTO.SerializeToString,
            eventoSolidario__pb2.EventoSolidario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEventoSolidario(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventoSolidarioService/DeleteEventoSolidario',
            eventoSolidario__pb2.EventoIdRequest.SerializeToString,
            eventoSolidario__pb2.EventoSolidario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEventoSolidarios(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventoSolidarioService/ListEventoSolidarios',
            usuario__pb2.Empty.SerializeToString,
            eventoSolidario__pb2.EventoSolidarioListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
