# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_client.src.Proto.Donacion import donacion_pb2 as grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_client/src/Proto/Donacion/donacion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DonacionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDonacion = channel.unary_unary(
                '/DonacionService/CreateDonacion',
                request_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.SerializeToString,
                response_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.FromString,
                _registered_method=True)
        self.GetDonacion = channel.unary_unary(
                '/DonacionService/GetDonacion',
                request_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionIdRequest.SerializeToString,
                response_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.Donacion.FromString,
                _registered_method=True)
        self.UpdateDonacion = channel.unary_unary(
                '/DonacionService/UpdateDonacion',
                request_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.SerializeToString,
                response_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.FromString,
                _registered_method=True)
        self.DeleteDonacion = channel.unary_unary(
                '/DonacionService/DeleteDonacion',
                request_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListDonaciones = channel.unary_unary(
                '/DonacionService/ListDonaciones',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionListResponse.FromString,
                _registered_method=True)


class DonacionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonacionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDonacion,
                    request_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.FromString,
                    response_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.SerializeToString,
            ),
            'GetDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDonacion,
                    request_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionIdRequest.FromString,
                    response_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.Donacion.SerializeToString,
            ),
            'UpdateDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDonacion,
                    request_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.FromString,
                    response_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.SerializeToString,
            ),
            'DeleteDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDonacion,
                    request_deserializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDonaciones,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DonacionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DonacionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DonacionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/CreateDonacion',
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.SerializeToString,
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/GetDonacion',
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionIdRequest.SerializeToString,
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.Donacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/UpdateDonacion',
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.SerializeToString,
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/DeleteDonacion',
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/ListDonaciones',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__client_dot_src_dot_Proto_dot_Donacion_dot_donacion__pb2.DonacionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
