# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import usuario_pb2 as usuario__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x1a\rusuario.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"_\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1b\n\x08username\x18\x02 \x01(\x0b\x32\t.Username\x12\x11\n\x03rol\x18\x03 \x01(\x0b\x32\x04.Rol\x12\r\n\x05token\x18\x04 \x01(\t26\n\x0cLoginService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=30
  _LOGINREQUEST._serialized_end=80
  _LOGINRESPONSE._serialized_start=82
  _LOGINRESPONSE._serialized_end=177
  _LOGINSERVICE._serialized_start=179
  _LOGINSERVICE._serialized_end=233
# @@protoc_insertion_point(module_scope)
