# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Usuario/usuario.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15Usuario/usuario.proto\"\x07\n\x05\x45mpty\"\x15\n\x03Rol\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"\x9f\x01\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\x12\x11\n\x03rol\x18\x08 \x01(\x0b\x32\x04.Rol\x12\x0e\n\x06\x61\x63tivo\x18\t \x01(\x08\"t\n\nUsuarioDTO\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x11\n\x03rol\x18\x07 \x01(\x0b\x32\x04.Rol\"1\n\x13UsuarioListResponse\x12\x1a\n\x08usuarios\x18\x01 \x03(\x0b\x32\x08.Usuario\"\x1c\n\x08Username\x12\x10\n\x08username\x18\x01 \x01(\t2\xdb\x01\n\x0eUsuarioService\x12)\n\rCreateUsuario\x12\x0b.UsuarioDTO\x1a\x0b.UsuarioDTO\x12!\n\nGetUsuario\x12\t.Username\x1a\x08.Usuario\x12)\n\rUpdateUsuario\x12\x0b.UsuarioDTO\x1a\x0b.UsuarioDTO\x12\"\n\rDeleteUsuario\x12\t.Username\x1a\x06.Empty\x12,\n\x0cListUsuarios\x12\x06.Empty\x1a\x14.UsuarioListResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Usuario.usuario_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=25
  _EMPTY._serialized_end=32
  _ROL._serialized_start=34
  _ROL._serialized_end=55
  _USUARIO._serialized_start=58
  _USUARIO._serialized_end=217
  _USUARIODTO._serialized_start=219
  _USUARIODTO._serialized_end=335
  _USUARIOLISTRESPONSE._serialized_start=337
  _USUARIOLISTRESPONSE._serialized_end=386
  _USERNAME._serialized_start=388
  _USERNAME._serialized_end=416
  _USUARIOSERVICE._serialized_start=419
  _USUARIOSERVICE._serialized_end=638
# @@protoc_insertion_point(module_scope)
