# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import usuario_pb2 as Usuario_dot_usuario__pb2


class UsuarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUsuario = channel.unary_unary(
                '/UsuarioService/CreateUsuario',
                request_serializer=Usuario_dot_usuario__pb2.UsuarioDTO.SerializeToString,
                response_deserializer=Usuario_dot_usuario__pb2.UsuarioDTO.FromString,
                )
        self.GetUsuario = channel.unary_unary(
                '/UsuarioService/GetUsuario',
                request_serializer=Usuario_dot_usuario__pb2.Username.SerializeToString,
                response_deserializer=Usuario_dot_usuario__pb2.Usuario.FromString,
                )
        self.UpdateUsuario = channel.unary_unary(
                '/UsuarioService/UpdateUsuario',
                request_serializer=Usuario_dot_usuario__pb2.UsuarioDTO.SerializeToString,
                response_deserializer=Usuario_dot_usuario__pb2.UsuarioDTO.FromString,
                )
        self.DeleteUsuario = channel.unary_unary(
                '/UsuarioService/DeleteUsuario',
                request_serializer=Usuario_dot_usuario__pb2.Username.SerializeToString,
                response_deserializer=Usuario_dot_usuario__pb2.Empty.FromString,
                )
        self.ListUsuarios = channel.unary_unary(
                '/UsuarioService/ListUsuarios',
                request_serializer=Usuario_dot_usuario__pb2.Empty.SerializeToString,
                response_deserializer=Usuario_dot_usuario__pb2.UsuarioListResponse.FromString,
                )


class UsuarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUsuario,
                    request_deserializer=Usuario_dot_usuario__pb2.UsuarioDTO.FromString,
                    response_serializer=Usuario_dot_usuario__pb2.UsuarioDTO.SerializeToString,
            ),
            'GetUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsuario,
                    request_deserializer=Usuario_dot_usuario__pb2.Username.FromString,
                    response_serializer=Usuario_dot_usuario__pb2.Usuario.SerializeToString,
            ),
            'UpdateUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUsuario,
                    request_deserializer=Usuario_dot_usuario__pb2.UsuarioDTO.FromString,
                    response_serializer=Usuario_dot_usuario__pb2.UsuarioDTO.SerializeToString,
            ),
            'DeleteUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUsuario,
                    request_deserializer=Usuario_dot_usuario__pb2.Username.FromString,
                    response_serializer=Usuario_dot_usuario__pb2.Empty.SerializeToString,
            ),
            'ListUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsuarios,
                    request_deserializer=Usuario_dot_usuario__pb2.Empty.FromString,
                    response_serializer=Usuario_dot_usuario__pb2.UsuarioListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsuarioService/CreateUsuario',
            Usuario_dot_usuario__pb2.UsuarioDTO.SerializeToString,
            Usuario_dot_usuario__pb2.UsuarioDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsuarioService/GetUsuario',
            Usuario_dot_usuario__pb2.Username.SerializeToString,
            Usuario_dot_usuario__pb2.Usuario.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsuarioService/UpdateUsuario',
            Usuario_dot_usuario__pb2.UsuarioDTO.SerializeToString,
            Usuario_dot_usuario__pb2.UsuarioDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsuarioService/DeleteUsuario',
            Usuario_dot_usuario__pb2.Username.SerializeToString,
            Usuario_dot_usuario__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsuarioService/ListUsuarios',
            Usuario_dot_usuario__pb2.Empty.SerializeToString,
            Usuario_dot_usuario__pb2.UsuarioListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
