# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc-client/src/Proto/Donaciones/donaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc-client/src/Proto/Donaciones/donaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1grpc-client/src/Proto/Donaciones/donaciones.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x02\n\x08\x44onacion\x12\n\n\x02id\x18\x01 \x01(\x03\x12%\n\tcategoria\x18\x02 \x01(\x0e\x32\x12.DonacionCategoria\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x03\x12\x11\n\teliminado\x18\x05 \x01(\x08\x12\x31\n\rfechaCreacion\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10usernameCreacion\x18\x07 \x01(\t\x12\x35\n\x11\x66\x65\x63haModificacion\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x14usernameModificacion\x18\t \x01(\t\"[\n\x0b\x44onacionDTO\x12%\n\tcategoria\x18\x02 \x01(\x0e\x32\x12.DonacionCategoria\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x03\"\x1f\n\x11\x44onacionIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"5\n\x14\x44onacionListResponse\x12\x1d\n\ndonaciones\x18\x01 \x03(\x0b\x32\t.Donacion*P\n\x11\x44onacionCategoria\x12\x08\n\x04ROPA\x10\x00\x12\r\n\tALIMENTOS\x10\x01\x12\x0c\n\x08JUGUETES\x10\x02\x12\x14\n\x10UTILES_ESCOLARES\x10\x03\x32\x9a\x02\n\x0f\x44onacionService\x12,\n\x0e\x43reateDonacion\x12\x0c.DonacionDTO\x1a\x0c.DonacionDTO\x12,\n\x0bGetDonacion\x12\x12.DonacionIdRequest\x1a\t.Donacion\x12,\n\x0eUpdateDonacion\x12\x0c.DonacionDTO\x1a\x0c.DonacionDTO\x12<\n\x0e\x44\x65leteDonacion\x12\x12.DonacionIdRequest\x1a\x16.google.protobuf.Empty\x12?\n\x0eListDonaciones\x12\x16.google.protobuf.Empty\x1a\x15.DonacionListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_client.src.Proto.Donaciones.donaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DONACIONCATEGORIA']._serialized_start=580
  _globals['_DONACIONCATEGORIA']._serialized_end=660
  _globals['_DONACION']._serialized_start=116
  _globals['_DONACION']._serialized_end=397
  _globals['_DONACIONDTO']._serialized_start=399
  _globals['_DONACIONDTO']._serialized_end=490
  _globals['_DONACIONIDREQUEST']._serialized_start=492
  _globals['_DONACIONIDREQUEST']._serialized_end=523
  _globals['_DONACIONLISTRESPONSE']._serialized_start=525
  _globals['_DONACIONLISTRESPONSE']._serialized_end=578
  _globals['_DONACIONSERVICE']._serialized_start=663
  _globals['_DONACIONSERVICE']._serialized_end=945
# @@protoc_insertion_point(module_scope)
